### ISSUE TITLE
question: compare sequences of strings with fastdtw

### ISSUE THREAD

**Issue by monperrus** [slaypni/fastdtw#18]
I want to compare sequences of string with fastdtw, typically the lines of a text file, as done by diff.

Is it possible? How would you do this?

Thanks.

**Comment by slaypni** [comment]
Maybe better to resort to `edit distance` which is used for calculating distance between 2 strings.
https://en.wikipedia.org/wiki/Levenshtein_distance

Perhaps, it is possible to use DTW for text similarity.
I found a paper:
https://www.ukp.tu-darmstadt.de/fileadmin/user_upload/Group_UKP/pics/p263-matuschek.pdf

**Comment by monperrus** [comment]
Thanks for your answer.
