### ISSUE TITLE
fastdtw and dtw giving different answers.

### ISSUE THREAD

**Issue by harsh244** [slaypni/fastdtw#20]
[timeseries1.xlsx](https://github.com/slaypni/fastdtw/files/2015986/timeseries1.xlsx)
[timeseries2.xlsx](https://github.com/slaypni/fastdtw/files/2015987/timeseries2.xlsx)

i tried fastdtw and dtw on the two timeseries that I have uploaded.Both are giving different answers. Should it give the same answer or am I missing out something?

**Comment by kernc** [comment]
@harsh244 It's good practice to explain briefly why the issue is no longer relevant before closing it.

**Comment by harsh244** [comment]
After reading the paper found out that it depends a lot on how we set the radius parameter so fasdtw may not always give us the best path as it is based on a lot of approximations ,the more we set the radius as the more closer the answer of our fasdtw to dtw ,at radius=(length of timeseries) ,fastdtw becomes dtw .
