### ISSUE TITLE
FutureWarning raised due to future incompatibility with numpy >= 1.14.0

### ISSUE THREAD

**Issue by mnicstruwig** [slaypni/fastdtw#32]
Python version: 3.7.1

It's quite an old issue, but I haven't seen it reported here yet (and it clutters up the output of scripts quite a bit).

When using the latest version (0.3.2) of  `fastdtw` and version of `numpy`>=1.14, a FutureWarning is raised:

Minimum working example:
```
In [1]: from fastdtw import fastdtw
In [2]: x = [1, 2, 3, 4, 5]
In [3]: y = [1, 2, 3, 4, 5]
In [10]: fastdtw(x, y)
/home/michael/miniconda3/envs/ds/bin/ipython:1: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  #!/home/michael/miniconda3/envs/ds/bin/python
Out[10]: (0.0, [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])
```

There are similarly related issues (that have since been resolved on the `h5py` project.
https://github.com/h5py/h5py/issues/961

Thanks!

**Comment by slaypni** [comment]
Thanks @mnicstruwig !
The warning might be already fixed thanks to the PR.

https://github.com/slaypni/fastdtw/pull/19

However, I did not update the package on pypi yet.
Sorry for inconvenience.

**Comment by mnicstruwig** [comment]
Ah ok, great!
I didn't realize --- thanks for the update. Looking forward to seeing the updated version on PyPi :)
